[luftdaten]
enabled = true
# Override the serial derived from the CPU
sensor  = "012345"

[influxdb]
enabled  = false
url      = "http://example.com:8086/write?precision=s&db=sensors"
username = "sensors"
password = "secret"
node     = "esp8266-123456"
