[luftdaten]
enabled = true
# Override the serial derived from the CPU
sensor  = "012345"

[influxdb]
enabled  = false
url      = "http://example.com:8086/write?precision=s&db=sensors"
username = "sensors"
password = "secret"
node     = "esp8266-123456"

[mqtt]
enabled   = false
broker    = "localhost"
port      = 1883
topic     = "/python/mqtt"
client_id = "dusty"
